name: Build and Release Binary

on:
  push:
    tags:
      - 'v*.*.*'  # triggers on semantic version tags like v1.2.3

permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/hamster ./cmd/server

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
