name: Build and Release Hamster

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Or whatever version you want

      - name: Build binary
        run: |
          go mod tidy
          go build -o hamster-linux-amd64 .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: hamster-linux-amd64
